version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:c1f7fbd0834eed5e69ea8e925ab59be61e68f278258df7cbbd652cb5516aacb7

node_8: &node_8
  docker:
    - image: node:8@sha256:9a42112281bef142cd40a281c5cd1b781cc9d0f0f2314827b87f86893f636df6

package_manager: &package_manager
  steps:
    - checkout
    - run: |
        echo "Required until 'npm' 5.2 is the oldest version used by a Node container."
        currentDirectory=$(pwd)
        mkdir -p /tmp/npm-install-directory
        cd /tmp/npm-install-directory
        npm install npm@latest --no-save
        rm -rf /usr/local/lib/node_modules
        mv node_modules /usr/local/lib/
        cd $currentDirectory
    - run: |
        echo "Required because Circle CI changes directory permissions to 777, and 'npm' won't install in that environment."
        npm install --unsafe-perm
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.npm
        key: dependencies
    - run: npm test && ($(npm bin)/codecov || echo "Codecov did not collect coverage reports")

jobs:
  node_6_job:
    <<: [*node_6, *package_manager]
  node_8_job:
    <<: [*node_8, *package_manager]

workflows:
  version: 2
  build:
    jobs:
      - node_6_job
      - node_8_job
