version: 2

node_4: &node_4
  docker:
    - image: node:4

node_6: &node_6
  docker:
    - image: node:6

node_8: &node_8
  docker:
    - image: node:8

npm: &npm
  steps:
    - checkout
    - restore_cache:
        keys:
          - dependencies
    - run: npm install
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.npm
        key: dependencies
    - run: npm test && ($(npm bin)/codecov || echo "Codecov did not collect coverage reports")

jobs:
  node_4_job:
    <<: [*node_4, *npm]
  node_6_job:
    <<: [*node_6, *npm]
  node_8_job:
    <<: [*node_8, *npm]

workflows:
  version: 2
  build:
    jobs:
      - node_4_job
      - node_6_job
      - node_8_job
