version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:4cdd9c14c85fee47fc48f5f660949ba761992f97abdf523161e110e63821a77c

node_8: &node_8
  docker:
    - image: node:8@sha256:918f0be3932f555cd2645ca828b9c231a2dab10d9cf2dbb58896411207bbe52f

package_manager: &package_manager
  steps:
    - checkout
    - run: |
        echo "Required until 'npm' 5.2 is the oldest version used by a Node container."
        currentDirectory=$(pwd)
        mkdir -p /tmp/npm-install-directory
        cd /tmp/npm-install-directory
        npm install npm@latest --no-save
        rm -rf /usr/local/lib/node_modules
        mv node_modules /usr/local/lib/
        cd $currentDirectory
    - run: |
        echo "Required because Circle CI changes directory permissions to 777, and 'npm' won't install in that environment."
        npm install --unsafe-perm
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.npm
        key: dependencies
    - run: npm test && ($(npm bin)/codecov || echo "Codecov did not collect coverage reports")

jobs:
  node_6_job:
    <<: [*node_6, *package_manager]
  node_8_job:
    <<: [*node_8, *package_manager]

workflows:
  version: 2
  build:
    jobs:
      - node_6_job
      - node_8_job
